elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  command: "logstash -f /opt/logstash/server/etc/conf.d/"
  image: docker-logstash:latest
#  volumes:
#    - ./logstash/config:/opt/logstash/server/etc/conf.d/
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  command: kibana
  image: kibana:latest
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
